### ISSUE TITLE
[Request] RevealHyperlinks

### ISSUE THREAD

**Issue by icrazykola** [Vencord/plugin-requests#132]
### Plugin Description

Reveals hyperlinks
Image: https://i.imgur.com/m7UmPwz.png

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
```css
.anchor_c8ddc0[title*="\a"]::after {
    content: " (" attr(href) ")";
    color: gray;
    font-size: 0.65em;
}
```
