### ISSUE TITLE
Blacklist specific GIFs locally

### ISSUE THREAD

**Issue by Kleins0** [Vencord/plugin-requests#154]
### Plugin Description

Blacklisting a specific GIF by having a clickable button of some sort.
This is useful for ex. NSFW GIFs so that you can hide/blur it with one click and never see that gif link again.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
You can achieve this with css.

[Screencast from 2024-03-04 22-25-48.webm](https://github.com/Vencord/plugin-requests/assets/45497981/39214fee-7f62-4579-88c3-79e280bf243d)

To add an additional gif, copy this part of the url for tenor links
![image](https://github.com/Vencord/plugin-requests/assets/45497981/8faa3528-cfc4-4877-a43e-ba9c8d1da028)
and this part for discord links
![image](https://github.com/Vencord/plugin-requests/assets/45497981/9e09f256-f9f0-4021-aa81-b7de7be7134c)

and add an additional `a[href*="..."]` line for both rules

```css
:is(
    a[href*="3387290697968250521"],
    a[href*="1206900124220006430"]
 ) + div {
    filter: blur(20px);
    transition: 200ms filter ease-in-out;
}

:is(
    a[href*="3387290697968250521"],
    a[href*="1206900124220006430"]
):hover + div {
    filter: blur(0);
}
```

feel free to change the filter to a stronger blur, a full opaque overlay, or a display none

or just consider not talking to people who send nsfw gifs :p
