### ISSUE TITLE
BetterChatNames

### ISSUE THREAD

**Issue by BaconCatBug** [Vencord/plugin-requests#259]
### Plugin Description

A plugin that Capitalises the channel names and replaces the hyphens with spaces.
![image](https://github.com/Vencord/plugin-requests/assets/4897163/f60a6c43-6865-43a6-98ef-046d2de46093)

### Existing Plugin for other mod

https://github.com/Break-Ben/BetterDiscordAddons/tree/main/BetterChatNames

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
This could probably just be done with CSS

**Comment by KrstlSkll69** [comment]
Don't know about capitalising channel names, but this replaces the dashes with spaces
https://discord.com/channels/1015060230222131221/1028106818368589824/1048275067278196836

**Comment by BaconCatBug** [comment]
> Don't know about capitalising channel names, but this replaces the dashes/hyphens with spaces https://discord.com/channels/1015060230222131221/1028106818368589824/1048275067278196836

Not really a solution if you use CSS to set a different font.

**Comment by EdVraz** [comment]
> > Don't know about capitalising channel names, but this replaces the dashes/hyphens with spaces https://discord.com/channels/1015060230222131221/1028106818368589824/1048275067278196836
> 
> Not really a solution if you use CSS to set a different font. (e.g. I use it to set all fonts to DejaVu Serif)

all the dashless font does is replace "-" with " " in the specified places; shouldn't interfere with anything else

**Comment by KrstlSkll69** [comment]
Exactly, took the words right out of my mouth

**Comment by BaconCatBug** [comment]
Yes, and I use a different font in those "specified places".
![image](https://github.com/Vencord/plugin-requests/assets/4897163/6addede6-d3ec-499e-baa5-7eca71f20f15)
![image](https://github.com/Vencord/plugin-requests/assets/4897163/151a3afa-2dc7-4ae0-ba3f-931377f21a0c)

**Comment by EdVraz** [comment]
If I change my font using [this](https://discord.com/channels/1015060230222131221/1028106818368589824/1048036626024116285) while having dashless enabled the selected font still is applied, so I'm not sure what the issue you have is.

**Comment by EdVraz** [comment]
Either way this should be completely doable with css alone

**Comment by BaconCatBug** [comment]
CSS Solution combined for anyone who googles this:


```css
[data-list-item-id^=channels___],
[class^=titleWrapper] > h1, 
[class^=resultChannel], 
[class^=channelMention], 
[class^=placeholder][class*=slateTextArea] 
{
        text-transform: capitalize;
}

@font-face {
    font-family: "Dashless";
    src: url("https://vendicated.github.io/random-files/Dashless.woff2") format("woff2");
}

[data-list-item-id^=channels___], /* channel list */
[class^=titleWrapper] > h1, /* top bar with topic */
[class^=resultChannel], /* channel name in search */
[class^=channelMention], /* channel mentions in chat */
[class^=placeholder][class*=slateTextArea] /* "Send a message in #blah" */
{
    font-family: "Dashless", var(--font-primary);
}
```
