### ISSUE TITLE
Plugin Request: ServerPings

### ISSUE THREAD

**Issue by waterbuffalowalking** [Vencord/plugin-requests#457]
### Plugin Description

Servers that have a ping automatically get sent to the top of the serverlist, just like an incoming DM 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
Try this:

```CSS
[aria-label="Servers"]
 { display: flex;
   flex-direction: column; }
[aria-label="Servers"] > [class^=listItem_]:has([aria-label*="mention"])
 { order: -1 }
```

**Comment by waterbuffalowalking** [comment]
@nvhhr This works well in English, if you could get it to work in Dutch I would greatly appreciate it 

Is there a way to get it above the - line, right where the DMs are normally incoming? And animation if possible? This is why I requested a plugin, not sure if it's possible

**Comment by nvhhr** [comment]
I'll make it work on all languages when I can.

As for getting it above the line, can't really be done without making it really hacky by recreating the separator or something, and an animation won't be possible.

It's also why I didn't add the 'can be done in css' tag to this, css can only get so far.

**Comment by waterbuffalowalking** [comment]
@nvhhr Thank you, should be able to help most people and me as temporarily but yes I'll leave this here incase anyone wants to make it more functional, something like the DM animation that makes it more noticeable would be really helpful for me

**Comment by Yakov5776** [comment]
Would be nice to have this but with a little twist: Only specific servers get bumped to the top of the list.

**Comment by nvhhr** [comment]
Ok this should work across any language, also bumps up folders to the top when pinged, and bumps up servers inside folders with and without betterfolders plugin.

```CSS
[data-list-id="guildsnav"] > [class^=scroller_] > [aria-label],
[id^=folder-items-]
 { display: flex; flex-direction: column; }
[data-list-id="guildsnav"] > [class^=scroller_] > [aria-label] :is([class^=listItem_],[class^=wrapper_]):has([class^=numberBadge_])
 { order: -1 }
```

A way to whitelist/blacklist servers for Yakov, after ``:has([class^=numberBadge_])`` add (with no space) ``:has([data-dnd-name*="ServerName Here"])`` or ``:not(:has([data-dnd-name*="ServerName Here"]))``

I hope this works because this was not the most fun to write and test :sweat_smile:
