### ISSUE TITLE
Channel color

### ISSUE THREAD

**Issue by Susuk0pii** [Vencord/plugin-requests#627]
### Plugin Description

It lets you change any channel color to however you want. If it's muted it would be a darker tone.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
this is very niche, you can recreate this with CSS though

(this is for the text on the channel buttons, which is what I think you were trying to target)

```css
[role="link"][data-list-item-id="channels___CHANNELID"] [class^="name_"] {
    --channels-default: #ffffff; // Non-muted channels
    --interactive-hover: #ffffff; // Hovered
    --interactive-active: #ffffff; // Focused in channel
    --interactive-muted: #ffffff; // Inactive muted channels
}
```

replace those colors with whatever you want, and make sure to set the `CHANNELID` to the ID of the channel
