### ISSUE TITLE
ServerHider

### ISSUE THREAD

**Issue by m4rc3lk00zak** [Vencord/plugin-requests#762]
### Plugin Description

Can you add serverhider plugin to vencord? like this one thats on betterdiscord
https://betterdiscord.app/plugin/ServerHider

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
honestly, either just leave the server, bury it deep in your server list or you can use something like this css (I cooked this up in 10 minutes idek if it's perfect)
```css
div[class^=listItem]:has(div[data-dnd-name]):has(div[data-list-item-id*='1015060230222131221']) { /* REPLACE THE NUMBER WITH THE SERVER ID */
    display: none !important;
}
```

also...
![image](https://github.com/Vencord/plugin-requests/assets/58668179/3f2ed9da-d853-43eb-b018-79b7ca2827a3)
![image](https://github.com/Vencord/plugin-requests/assets/58668179/b83db76c-78eb-4229-8281-af61a178e47e)
