### ISSUE TITLE
CollapsibleUI

### ISSUE THREAD

**Issue by zany130** [Vencord/plugin-requests#79]
### Features
* Members list style collapsing of most UI elements
* Dynamic uncollapsing of hidden elements on hover
* Autocollapse for parts of the Discord UI based on window size
* Out-of-the-box compatibility with most themes and plugins
* Keyboard shortcuts for most actions
* Resizable channel/DMs list
* Smooth transition effects
* And most importantly, ___everything___ is customizable

### Existing Plugin for other mod

https://github.com/programmer2514/BetterDiscord-CollapsibleUI/tree/main

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by zany130** [comment]
yes this can be done in css but I haven't found one that works with most themes

**Comment by EdVraz** [comment]
If it can be done with css and you are unhappy with the existing theme consider making your own theme :) there's also a channel on the discord designated to css development.

**Comment by zany130** [comment]
but would it possible to auto collapse based on window size in CSS?

> If it can be done with css and you are unhappy with the existing theme consider making your own theme :) there's also a channel on the discord designated to css development.

**Comment by TheKodeToad** [comment]
Oh I didn't notice it had been closed and opened this (from my wip branch) https://github.com/Vendicated/Vencord/pull/2193 lol

**Comment by EdVraz** [comment]
> Oh I didn't notice it had been closed and opened this (from my wip branch) [Vendicated/Vencord#2193](https://github.com/Vendicated/Vencord/pull/2193) lol

Feel free to reopen I just felt a bit much like this is doable by css alone by their comment ^^'

**Comment by TheKodeToad** [comment]
Only you or another collaborator can open :P (not even the issue author if a collaborator closed it)

**Comment by zany130** [comment]
FWIW i sort of got this working with CSS with some help

only thing I didn't get working correctly is the channel list hover hide (it collapses fine when the window becomes to small)

and the user area hover hide
```css
// auto collapse channels on  window size
.sidebar_ded4b5 {
    display: block;
  }
  @media (max-width: 1000px) {
    .sidebar_ded4b5 {
      display: none;
    }
  }


// auto collapse Members on  window size
.members__9f47b {
    display: block;
  }
  @media (max-width: 1000px) {
    .members__9f47b {
      display: none;
    }
  }
.container__4f20e {
    display: block;
  }
  @media (max-width: 1000px) {
    .container__4f20e {
      display: none;
    }
  }


/* small channel list */
.sidebar_ded4b5:hover {
   transition-delay: 0s;
   width: var(--channel-max)!important;
   padding-left: initial!important;
}
/* edit it */
:root {
    --channel-mini: 0px;
    --channel-max: 240px; /* normal channel list size */}


/* small server list */
.guilds__2b93a {
    height: 0px!important;
    padding-left: var(--guild-mini)!important;
    transition: all 0.3s; /* smoothest slide in the west */
}
.guilds__2b93a:hover {
    transition-delay: 0.1s;
    height: var(--guild-max)!important;
    padding-left: initial!important;
}
/* edit it */
:root {
    --guild-mini: 40px;
    --guild-max: 72px; /* normal server list size */ }


/* auto hide messagebar */
.channelTextArea__2e60f {
    transition-delay: 0s;
    height: var(--bar-mini)!important;
    padding-left: initial!important;
}
.channelTextArea__2e60f:hover {
    transition-delay: 0s;
    height: var(--bar-max)!important;
    padding-left: initial!important;
}
/* edit it */
:root {
    --bar-mini: 20px;
    --bar-max: 50px; /* normal channel list size */}


// autohide user area
.container_ca50b9 {
    transition-delay: 0s;
    height: var(--user-mini)!important;
    padding-left: initial!important;
}
.container_ca50b9:hover {
    transition-delay: 0s;
    height: var(--user-max)!important;
    padding-left: initial!important;
}
/* edit it */
:root {
    --user-mini: 24px;
    --user: 240px; /* normal channel list size */}
```
