### ISSUE TITLE
Block Messages from New Server Members

### ISSUE THREAD

**Issue by Feathers8** [Vencord/plugin-requests#855]
### Plugin Description

Those with the green "new member leaf" icon next to their name.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
```css
/* Remove messages from new members */
[id^="chat-messages"]:has(.newMemberBadge_ed263a) {
  display: none;
}
```
