### ISSUE TITLE
Show status in chat

### ISSUE THREAD

**Issue by zumbiepig** [Vencord/plugin-requests#873]
### Plugin Description

Make it so you can see other people's status in a chat so you don't have to click on them.

Like this: 
![image](https://github.com/Vencord/plugin-requests/assets/121742281/ed7dfff1-972d-41bf-a698-3a1b6db85237)
but in the channel
![image](https://github.com/Vencord/plugin-requests/assets/121742281/ce992995-4f14-4d5d-af7b-6c2e8e8752cb)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/55350217/e4bff880-9a18-4d56-a841-fb3910e8ed36)
![image](https://github.com/Vencord/plugin-requests/assets/55350217/e397ae0f-4980-4e3d-bbff-8520bd3185cb)

**Comment by cheesesamwich** [comment]
> @Krammeth I want the bubble status, not the globe/phone icon.

It still has the same functionality, if not more

**Comment by nvhhr** [comment]
There are a few ways to sort of do this in css by utilizing the platformindicator, here's a jank prototype I threw together which hides the icons and creates an arbitrarily placed circle with the same color:

```CSS
.header_f9f2ca { overflow: visible !important; }
.contents_f9f2ca .vc-platform-indicator { display: none; }
.contents_f9f2ca:has(.vc-platform-indicator)>.header_f9f2ca::after
 { content: "";
   height:10px;
   width:10px;
   border-radius: 50%;
   position: absolute;
   left: -29px;
   top: 30px;
   z-index: 1;
   border: 4px solid var(--background-primary); }
.contents_f9f2ca:has(.vc-platform-indicator>[fill="#f0b232"])>.header_f9f2ca::after{background: #f0b232;}
.contents_f9f2ca:has(.vc-platform-indicator>[fill="#f23f43"])>.header_f9f2ca::after{background: #f23f43;}
.contents_f9f2ca:has(.vc-platform-indicator>[fill="#23a55a"])>.header_f9f2ca::after{background: #23a55a;}
```
![image](https://github.com/Vencord/plugin-requests/assets/34724502/289abf83-2663-4768-8cf7-5763f788700c)
