### ISSUE TITLE
Replace App to Bot

### ISSUE THREAD

**Issue by Steve78392** [Vencord/plugin-requests#887]
### Plugin Description

replacing "app" in bot's tag with a better name: "Bot"

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Faf4a** [comment]
possible with css (somewhat)
```css
[class*="botText_"] {
    font-size: 10px;
    visibility: hidden;
    position: relative;
}

[class*="botText_"]::before {
    content: "BOT";
    visibility: visible;
    position: absolute;
}
```
