### ISSUE TITLE
ShowMeYourName: Hover on message to show nick

### ISSUE THREAD

**Issue by WNnitro** [Vencord/plugin-requests#915]
### Plugin Description

add a toggle-able feature so that instead of showing everyone's username at once, only show it when the user hovers over someone's message

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [ ] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
actually was pretty easy

```css
.vc-smyn-suffix {
    display: none;
}
div[class^="message_"]:hover .vc-smyn-suffix {
    display: inline;
}
```
