### ISSUE TITLE
RuleOfThirdsPreview

### ISSUE THREAD

**Issue by Grey421** [Vencord/plugin-requests#927]
### Plugin Description

A rule of thirds filter over the crop preview when setting a new profile picture - like the one seen on vanilla Discord mobile.

This'd be useful for making it easier to effectively crop a profile picture and have a perspective while cropping on what it would look like in practice.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
you can achieve this with css.

here's a simple example, you can make it look better:
```css
.overlayAvatar_ba5b9e {
    &::before {
        position: absolute;
        background: var(--white-500);
        content: "";
        top: 33%;
        left: 0;
        width: 100%;
        height: .3rem;
        box-shadow: 0 8rem 0 var(--white-500);
    }

    &::after {
        position: absolute;
        background: var(--white-500);
        content: "";
        top: 0;
        left: 33%;
        width: .3rem;
        height: 100%;
        box-shadow: 10rem 0 0 var(--white-500);
    }
}
```
