### ISSUE TITLE
Hide other users' statuses

### ISSUE THREAD

**Issue by Feannay** [Vencord/plugin-requests#967]
### Plugin Description

I'd like if possible a way to disable seeing status from other people manually, like being able to right click the user and have an option to stop seeing their custom statuses. This may look niche, but I've seen a lot of people (including on the discordapp reddit) requesting this feature, including myself. Some people tend to have custom statuses that make me uncomfortable and I'd love a way to stop seeing them, for now I just straight up hide the users list, but this isn't ideal, mostly when some of those people are in my friendslists. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
Pretty sure it can be done with css, also #480

**Comment by Krammeth** [comment]
took me a bit to cook, but this should work
```css
/* hide specific users' status */
[src*="ID"] /* <- create a copy of [src*="ID"] to add more people, use commas to separate them */
  { [class^=avatarStack_] > & 
    { [class^=member_] [class^=memberInner_]:has(&) [class^=content_] [class^=subText_] > [class^=activity_], /* memberlist */
      [class^=privateChannels_] > [class^=scroller_] [class^=content_] > [class^=channel_]:has(&) [class^=subText_] /* DMs list */
        { display: none; } 
      [class^=userPopoutInner_] header:has(&), /* popout */
      [class^=userPanelInner_] header:has(&) /* DMs panel */ 
        { & [class^=invisibleContainer_],
          & > div:not([class]) > [class^=visibleContainer] 
            { display: none; } } } }
```

**Comment by Feannay** [comment]
Omg thank you so much!! I don't know a thing about coding so this truly helped! And sorry I didn't see that one plugin request although I searched! I used the css you sent and it works well! 

It still displays status in the friendlist though, is there something I can add/change to hide them completely? 

Other than that it's perfect thank you so much!

**Comment by Krammeth** [comment]
> It still displays status in the friendlist though
oop, good catch, I forgot about that part, I'll edit my previous message with the fix in a bit

**Comment by Krammeth** [comment]
fixed, should work fine now
let me know if I missed anything else

**Comment by Feannay** [comment]
It works perfectly!! Thank you so much for the quick response!!

**Comment by Krammeth** [comment]
You're welcome, it was fun to make 👍

**Comment by Krammeth** [comment]
turns out I had also forgot about the full popout status, so here you go
```css
/* hide specific users' status */
[src*="ID"] { /* <- copy the [src*="ID"] to add more people */
  [class^=avatarStack_] > & { 
    [class^=member_] [class^=memberInner_]:has(&) [class^=content_] [class^=subText_] > [class^=activity_], /* memberlist */
    [class^=privateChannels_] > [class^=scroller_] [class^=content_] > [class^=channel_]:has(&) [class^=subText_], /* DMs list */
    [class^=peopleListItem_] [class^=userInfo_]:has(&) [class^=subtext_] { /* friends list */
      display: none; 
    } 
    [class^=userPopoutInner_] header:has(&), /* popout */
    [class^=userProfileModalInner_] header:has(&), /* full popout */
    [class^=userPanelInner_] header:has(&) { /* DMs panel */ 
      & div:not([class]) {
        & > [class^=invisibleContainer_],
        & > [class^=visibleContainer_] { 
        display: none; 
        } 
      } 
    } 
  }
}
```
